
namespace FAForever.Replay
{
    /// <summary>
    /// Unit display names, mirrored from the FAF game repository: the Description field of
    /// units/*_unit.bp (e.g. "Armored Command Unit" for uel0001). The table itself lives in
    /// UnitNames.g.cs, generated by tools/generate-unit-names.ps1; re-run it after a game
    /// update. Mod units are not in the table.
    /// </summary>
    public static partial class UnitNames
    {
        /// <summary>
        /// The display name for a blueprint id (case-insensitive), or null when unknown.
        /// </summary>
        public static string? GetOrNull(string? blueprintId)
            => blueprintId is { Length: > 0 } && Names.TryGetValue(blueprintId.ToLowerInvariant(), out string? name) ? name : null;
    }
}
