<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FAForever.FileFormats.Replay\FAForever.FileFormats.Replay.csproj" />
  </ItemGroup>

</Project>
