using System.Net.Http.Json;

namespace FAForever.Replay.Viewer.Services.Units;

/// <summary>
/// Cell positions of the unit icons and layer backgrounds in the sprite atlases under
/// wwwroot/images/units, generated by tools/convert-unit-icons.ps1. The JSON indexes are fetched
/// once and shared by every <c>UnitIcon</c> on the page.
/// </summary>
public sealed class UnitIconAtlas(HttpClient http)
{
    public const string UnitsImage = "images/units/units-atlas.png";
    public const string BackgroundsImage = "images/units/backgrounds-atlas.png";

    /// <summary>The icon of units without one of their own (mods, campaign units).</summary>
    public const string DefaultIcon = "default";

    public sealed record Cell(int X, int Y);

    public sealed record Index(int CellSize, int Columns, int Rows, Dictionary<string, Cell> Icons)
    {
        public int Width => Columns * CellSize;
        public int Height => Rows * CellSize;
    }

    private Task<(Index Units, Index Backgrounds)>? loading;

    public Task<(Index Units, Index Backgrounds)> LoadAsync() => loading ??= LoadCoreAsync();

    private async Task<(Index Units, Index Backgrounds)> LoadCoreAsync()
    {
        Task<Index?> units = http.GetFromJsonAsync<Index>("images/units/units-atlas.json");
        Task<Index?> backgrounds = http.GetFromJsonAsync<Index>("images/units/backgrounds-atlas.json");
        return (
            await units ?? throw new InvalidOperationException("The unit icon atlas index is empty."),
            await backgrounds ?? throw new InvalidOperationException("The background atlas index is empty."));
    }

    /// <summary>
    /// The atlas key of a blueprint id; ids from replays may differ in case from the icon names.
    /// </summary>
    public static string IconKey(string blueprintId) => blueprintId.ToLowerInvariant();

    /// <summary>
    /// The layer background of a blueprint (<c>land</c>, <c>air</c> or <c>sea</c>). The game takes it
    /// from <c>General.Icon</c> in the blueprint, which a replay does not contain, so it is derived
    /// from the id via <see cref="FAForever.Replay.Blueprints.GetLayer"/>. Structures and amphibious
    /// units fall back to land.
    /// </summary>
    public static string Layer(string blueprintId) => FAForever.Replay.Blueprints.GetLayer(blueprintId) switch
    {
        FAForever.Replay.BlueprintLayer.Air => "air",
        FAForever.Replay.BlueprintLayer.Naval => "sea",
        _ => "land",
    };
}
