#!/usr/bin/env pwsh
# Generates src/FAForever.FileFormats.Blueprints/UnitNames.g.cs from the blueprint files of the FAF game
# repository. The name of a unit is the Description field of its *_unit.bp, e.g.
#   Description = "<LOC uel0001_desc>Armored Command Unit",
# with the localisation marker stripped. Output is deterministic (sorted by id), so the
# diff after a game update only shows real changes.
param(
    [string]$Source = "D:\faf-development\fa\units"
)

$ErrorActionPreference = "Stop"

$target = Join-Path $PSScriptRoot "..\src\FAForever.FileFormats.Blueprints\UnitNames.g.cs"
$pattern = 'Description\s*=\s*"(?:<LOC\s+[^>]+>)?([^"]*)"'

$entries = Get-ChildItem -Path $Source -Recurse -Filter "*_unit.bp" | ForEach-Object {
    $id = $_.BaseName -replace '_unit$', ''
    $match = Select-String -Path $_.FullName -Pattern $pattern | Select-Object -First 1
    if ($match -and $match.Matches[0].Groups[1].Value.Trim()) {
        [pscustomobject]@{
            Id   = $id.ToLowerInvariant()
            Name = $match.Matches[0].Groups[1].Value.Trim()
        }
    }
} | Sort-Object Id

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine("// <auto-generated>")
[void]$builder.AppendLine("// Generated by tools/generate-unit-names.ps1 from the FAF game repository (units/*_unit.bp,")
[void]$builder.AppendLine("// the Description field). Do not edit by hand; re-run the script after a game update.")
[void]$builder.AppendLine("// </auto-generated>")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("namespace FAForever.FileFormats.Blueprints")
[void]$builder.AppendLine("{")
[void]$builder.AppendLine("    public static partial class UnitNames")
[void]$builder.AppendLine("    {")
[void]$builder.AppendLine("        private static readonly Dictionary<string, string> Names = new()")
[void]$builder.AppendLine("        {")
foreach ($entry in $entries) {
    $name = $entry.Name -replace '\\', '\\\\' -replace '"', '\"'
    [void]$builder.AppendLine("            [`"$($entry.Id)`"] = `"$name`",")
}
[void]$builder.AppendLine("        };")
[void]$builder.AppendLine("    }")
[void]$builder.AppendLine("}")

# LF line endings, no BOM: keep the generated file byte-stable across environments.
$text = $builder.ToString() -replace "`r`n", "`n"
[System.IO.File]::WriteAllText((Resolve-Path (Split-Path $target) | Join-Path -ChildPath (Split-Path $target -Leaf)), $text, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $($entries.Count) unit names to $target"
